import React, { createContext, useState, useContext, useEffect } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

// Theme colors
export const themes = {
  orange: {
    primary: "#E58E26",
    secondary: "#FF6B6B",
    accent: "#FFA500",
    text: "#333",
    background: "#FFF5E6", // Light orange background
    lightBg: "#FFEBCC",
    aiGradient: ["#FFD700", "#FFA500", "#FF8C00"], // Gold AI gradient
  },
  blue: {
    primary: "#4A90E2",
    secondary: "#2196F3",
    accent: "#03A9F4",
    text: "#333",
    background: "#E3F2FD", // Light blue background
    lightBg: "#BBDEFB",
    aiGradient: ["#00D4FF", "#0099FF", "#0066FF"], // Cyan AI gradient
  },
  green: {
    primary: "#28A745",
    secondary: "#4CAF50",
    accent: "#66BB6A",
    text: "#333",
    background: "#E8F5E9", // Light green background
    lightBg: "#C8E6C9",
    aiGradient: ["#00E676", "#00C853", "#00A344"], // Bright green AI gradient
  },
  purple: {
    primary: "#9C27B0",
    secondary: "#AB47BC",
    accent: "#BA68C8",
    text: "#333",
    background: "#F3E5F5", // Light purple background
    lightBg: "#E1BEE7",
    aiGradient: ["#E040FB", "#D500F9", "#AA00FF"], // Bright purple AI gradient
  },
  red: {
    primary: "#DC3545",
    secondary: "#F44336",
    accent: "#E57373",
    text: "#333",
    background: "#FFEBEE", // Light red background
    lightBg: "#FFCDD2",
    aiGradient: ["#FF6B6B", "#FF4444", "#FF1744"], // Bright red AI gradient
  },
};

// Translations
export const translations = {
  vi: {
    // Common
    home: "Trang chủ",
    orders: "Đơn hàng",
    products: "Sản phẩm",
    account: "Tài khoản",
    cart: "Giỏ hàng",
    settings: "Cài đặt",
    logout: "Đăng xuất",
    search: "Tìm kiếm",
    save: "Lưu",
    cancel: "Hủy",
    delete: "Xóa",
    edit: "Sửa",
    add: "Thêm",
    confirm: "Xác nhận",
    back: "Quay lại",
    all: "Tất cả",
    detail: "Chi tiết",
    statistics: "Thống kê",
    total: "Tổng cộng",

    // Admin
    dashboard: "Dashboard Quản Trị",
    orderManagement: "Quản Lý Đơn Hàng",
    productManagement: "Quản Lý Sản Phẩm",
    systemSettings: "Cài đặt hệ thống",
    overview: "Tổng quan hoạt động",
    detailedStatistics: "Thống Kê Chi Tiết",
    personalInfo: "Cá nhân",
    management: "Quản Lý",
    revenue: "Doanh Thu",
    customers: "Khách hàng",
    totalOrders: "Tổng đơn hàng",
    totalRevenue: "Tổng doanh thu",
    totalProducts: "Tổng sản phẩm",

    // Order status
    pending: "Chờ xác nhận",
    processing: "Đang xử lý",
    completed: "Hoàn thành",
    cancelled: "Đã hủy",

    // Actions
    confirmOrder: "Xác nhận",
    completeOrder: "Hoàn thành",
    cancelOrder: "Hủy",
    viewDetail: "Chi tiết",

    // Settings
    theme: "Chủ đề",
    language: "Ngôn ngữ",
    notifications: "Thông báo",
    orderNotifications: "Thông báo đơn hàng",
    dataManagement: "Dữ liệu",
    appearance: "Giao diện",
    information: "Thông tin",
    version: "Phiên bản",
    backupData: "Sao lưu dữ liệu",
    clearCache: "Xóa bộ nhớ đệm",
    chooseTheme: "Chọn chủ đề",
    chooseLanguage: "Chọn ngôn ngữ",

    // Messages
    success: "Thành công",
    error: "Lỗi",
    loading: "Đang tải...",
    loadingOrders: "Đang tải đơn hàng...",
    loadingProducts: "Đang tải sản phẩm...",
    noData: "Chưa có dữ liệu",
    noOrders: "Chưa có đơn hàng nào",
    confirmOrderMessage: "Bạn có chắc chắn muốn xác nhận đơn hàng này?",
    completeOrderMessage: "Xác nhận đơn hàng đã được giao thành công?",
    cancelOrderMessage: "Bạn có chắc muốn hủy đơn hàng này?",
    confirmDeleteProduct: "Bạn có chắc muốn xóa sản phẩm",
    paymentProof: "Ảnh xác nhận chuyển khoản",
    no: "Không",
    productAdded: "Đã thêm sản phẩm mới",
    productDeleted: "Đã xóa sản phẩm",
    cannotDeleteProduct: "Không thể xóa sản phẩm",
    addProduct: "Thêm Sản Phẩm",
    editProduct: "Sửa Sản Phẩm",
    deleteProduct: "Xóa sản phẩm",
    confirmLogout: "Bạn có chắc muốn đăng xuất khỏi tài khoản admin?",
    cannotLogout: "Không thể đăng xuất. Vui lòng thử lại.",
    admin: "Admin",
    email: "Email",
    role: "Vai trò",
    administrator: "Quản trị viên",
    viewPendingOrders: "Xem đơn hàng chờ xác nhận",
    configureApp: "Cấu hình ứng dụng",
    support: "Hỗ Trợ",
    help: "Trợ giúp",
    userGuide: "Hướng dẫn sử dụng",
    aboutApp: "Về ứng dụng",
    aboutBakeryApp: "Về BakeryApp Admin",
    bakeryManagementApp: "Ứng dụng quản lý cửa hàng bánh",
    searchProducts: "Tìm kiếm sản phẩm...",
    stock: "Tồn kho",
    noProductsFound: "Không tìm thấy sản phẩm",
    noProducts: "Chưa có sản phẩm nào",
    productName: "Tên Sản Phẩm",
    enterProductName: "Nhập tên sản phẩm",
    price: "Giá",
    enterPrice: "Nhập giá sản phẩm",
    description: "Mô Tả",
    enterDescription: "Nhập mô tả sản phẩm",
    category: "Danh Mục",
    imageURL: "URL Ảnh Sản Phẩm",
    preview: "Xem trước",
    cannotLoadProducts: "Không thể tải danh sách sản phẩm",
    fillRequiredFields: "Vui lòng điền đầy đủ thông tin bắt buộc",
    productUpdated: "Đã cập nhật sản phẩm",
    cannotSaveProduct: "Không thể lưu sản phẩm",
    cannotLoadOrders: "Không thể tải danh sách đơn hàng",
    orderStatusUpdated: "Đã cập nhật trạng thái đơn hàng thành",
    cannotUpdateOrderStatus: "Không thể cập nhật trạng thái đơn hàng",
    themeChanged: "Chủ đề đã được thay đổi thành công!",
    cannotChangeTheme: "Không thể thay đổi chủ đề",
    languageChanged: "Ngôn ngữ đã được thay đổi thành công!",
    cannotChangeLanguage: "Không thể thay đổi ngôn ngữ",
    clearCacheTitle: "Xóa bộ nhớ đệm",
    clearCacheMessage:
      "Bạn có chắc muốn xóa bộ nhớ đệm? Điều này sẽ đăng xuất bạn khỏi ứng dụng.",
    cacheCleared: "Đã xóa bộ nhớ đệm",
    cannotClearCache: "Không thể xóa bộ nhớ đệm",
    viewAllPendingOrders: "Xem tất cả đơn hàng chờ xác nhận",
    freeStorage: "Giải phóng không gian lưu trữ",
    noNotifications: "Không có thông báo mới",
    pendingOrdersHere: "Các đơn hàng chờ xác nhận sẽ hiển thị ở đây",
    cannotLoadCategories: "Không thể tải danh sách danh mục",
    enterCategoryName: "Vui lòng nhập tên danh mục",
    categoryUpdated: "Đã cập nhật danh mục",
    categoryAdded: "Đã thêm danh mục mới",
    cannotSaveCategory: "Không thể lưu danh mục",
    deleteCategory: "Xóa danh mục",
    confirmDeleteCategory: "Bạn có chắc muốn xóa danh mục",
    categoryDeleteNote:
      "Lưu ý: Các sản phẩm thuộc danh mục này sẽ không bị xóa.",
    categoryDeleted: "Đã xóa danh mục",
    cannotDeleteCategory: "Không thể xóa danh mục",
    addCategory: "Thêm danh mục",
    editCategory: "Sửa danh mục",
    categoryName: "Tên danh mục",
    enterCategory: "Nhập tên danh mục",
    categoryDescription: "Mô tả danh mục",
    enterCategoryDescription: "Nhập mô tả (tùy chọn)",
    categoryIcon: "Icon danh mục",
    iconName: "Tên icon",
    enterIconName: "VD: pizza, fast-food, cafe",
    noCategories: "Chưa có danh mục nào",
    downloadYourData: "Tải xuống dữ liệu của bạn",
    notification: "Thông báo",
    featureInDevelopment: "Tính năng đang được phát triển",
    searchByPhone: "Tìm theo số điện thoại...",

    // User screens
    myCart: "Giỏ hàng của bạn",
    emptyCart: "Giỏ hàng trống",
    emptyCartMessage: "Hãy thêm sản phẩm vào giỏ hàng",
    removeFromCart: "Xóa sản phẩm",
    confirmRemoveFromCart: "Xóa khỏi giỏ hàng?",
    checkout: "Thanh toán",
    checkBeforeOrder: "Kiểm tra lại trước khi đặt món nhé!",
    selectAll: "Chọn tất cả",
    continueShopping: "Tiếp tục mua sắm",
    emptyCartSubtitle: "Hãy thêm vài chiếc bánh ngon vào giỏ nhé 🍰",
    orderNow: "Đặt hàng ngay",
    totalAmount: "Tổng cộng",
    outOfStock: "Hết hàng",
    exceedsStock: "Vượt quá tồn kho",
    onlyXInStock: "Chỉ còn",
    inStock: "sản phẩm trong kho.",
    deleteProductFromCart: "Xóa sản phẩm",
    confirmDelete: "Xóa",
    pleaseSelectProducts: "Vui lòng chọn ít nhất 1 sản phẩm để thanh toán",
    myOrders: "Đơn hàng của tôi",
    orderHistory: "Lịch sử đơn hàng",
    orderDetail: "Chi tiết đơn hàng",
    orderCode: "Mã đơn hàng",
    noOrdersYet: "Chưa có đơn hàng nào",
    ordersWillShowHere: "Các đơn hàng của bạn sẽ hiển thị ở đây",
    completedOrdersHere: "Lịch sử các đơn hàng đã hoàn thành sẽ hiển thị ở đây",
    orderNotFound: "Không tìm thấy đơn hàng",
    cancelOrderTitle: "Hủy đơn hàng",
    confirmCancelOrder: "Bạn có chắc chắn muốn hủy đơn hàng này?",
    orderCancelled: "Đã hủy đơn hàng",
    cannotCancelOrder: "Không thể hủy đơn hàng. Vui lòng thử lại.",
    confirmReceived: "Xác nhận đã nhận hàng",
    confirmReceivedMessage:
      "Bạn đã nhận được hàng và hài lòng với đơn hàng này?",
    thankYou: "Cảm ơn bạn!",
    orderCompleted: "Đơn hàng đã hoàn thành",
    reorder: "Mua lại",
    cannotReorder: "Không thể tạo lại đơn hàng",
    noProductsInOrder: "Không có sản phẩm nào",
    accountNumber: "Số tài khoản",
    accountHolder: "Chủ tài khoản",
    pleaseCheckBank: "Vui lòng kiểm tra tài khoản ngân hàng và xác nhận khi đã",
    addToCart: "Thêm vào giỏ hàng",
    pleaseLogin: "Vui lòng đăng nhập để thêm sản phẩm vào giỏ hàng!",
    addedToCart: "Đã thêm vào giỏ hàng!",
    noDescription: "Không có mô tả.",
    profile: "Cá nhân",
    myAccount: "Tài khoản của tôi",
    login: "Đăng nhập",
    register: "Đăng ký",
    createAccount: "Tạo tài khoản mới",
    alreadyHaveAccount: "Đã có tài khoản?",
    noAccountYet: "Chưa có tài khoản?",
    creating: "Đang tạo tài khoản...",
    personalInformation: "Thông tin cá nhân",
    phoneNumber: "Số điện thoại",
    notAvailable: "Chưa có",
    deliveryAddress: "Địa chỉ giao hàng",
    addDeliveryAddress: "Thêm địa chỉ giao hàng",
    manageOrders: "Quản lý đơn hàng",
    orderProcessing: "Đang xử lý",
    orderHistoryTab: "Lịch sử",
    purchased: "Đã mua",
    notLoggedIn: "Bạn chưa đăng nhập",
    loginToExperience: "Đăng nhập để trải nghiệm đầy đủ tính năng",
    signUpAccount: "Đăng ký tài khoản",
    confirmLogoutTitle: "Xác nhận đăng xuất",
    confirmLogoutMessage:
      "Bạn có chắc chắn muốn đăng xuất khỏi tài khoản không?",
    user: "Người dùng",
    hello: "Xin chào",
    bakeryAppName: "Bakery App",
    deliverySlogan: "Đặt bánh ngon, giao tận nơi cho bạn 🍰",
    searchPlaceholder: "Tìm bánh bạn yêu thích...",
    searchHistory: "🕓 Lịch sử tìm kiếm",
    clear: "Xóa",
    noSearchHistory: "Chưa có lịch sử tìm kiếm.",
    suggestionsForYou: "🔥 Gợi ý cho bạn",
    featuredCategories: "🎂 Danh mục nổi bật",
    hotThisWeek: "🔥 Món hot trong tuần",
    loadingData: "Đang tải dữ liệu...",
    // Login & SignUp
    emailLabel: "Email",
    enterEmail: "Nhập email",
    passwordLabel: "Mật khẩu",
    enterPassword: "Nhập mật khẩu",
    fullName: "Họ và tên",
    enterFullName: "Nhập họ và tên",
    phone: "Số điện thoại",
    enterPhone: "Nhập số điện thoại",
    confirmPassword: "Xác nhận mật khẩu",
    enterConfirmPassword: "Nhập lại mật khẩu",
    forgotPassword: "Quên mật khẩu?",
    loginButton: "Đăng nhập",
    signUpButton: "Đăng ký",
    loggingIn: "Đang đăng nhập...",
    signingUp: "Đang đăng ký...",
    resetPassword: "Đặt lại mật khẩu",
    sendResetEmail: "Gửi email đặt lại",
    emailRequired: "Vui lòng nhập email",
    emailInvalid: "Email không hợp lệ",
    passwordRequired: "Vui lòng nhập mật khẩu",
    passwordTooShort: "Mật khẩu phải có ít nhất 6 ký tự",
    fullNameRequired: "Vui lòng nhập họ và tên",
    phoneRequired: "Vui lòng nhập số điện thoại",
    phoneInvalid: "Số điện thoại không hợp lệ",
    passwordsNotMatch: "Mật khẩu không khớp",
    loginSuccess: "Đăng nhập thành công!",
    signUpSuccess: "Đăng ký thành công!",
    resetEmailSent: "Email đặt lại mật khẩu đã được gửi!",
    loginError: "Đăng nhập thất bại",
    signUpError: "Đăng ký thất bại",
    resetError: "Không thể gửi email đặt lại",
    // Product Detail
    backButton: "Quay lại",
    addToCartButton: "Thêm vào giỏ hàng",
    buyNow: "Mua ngay",
    quantity: "Số lượng",
    increase: "Tăng",
    decrease: "Giảm",
    productOutOfStock: "Hết hàng",
    productDescription: "Mô tả sản phẩm",
    // Checkout
    checkoutPage: "Thanh toán",
    orderSummary: "Tóm tắt đơn hàng",
    recipientInfo: "Thông tin người nhận",
    recipientName: "Tên người nhận",
    recipientPhone: "Số điện thoại người nhận",
    shippingAddress: "Địa chỉ giao hàng",
    enterAddress: "Nhập địa chỉ giao hàng",
    paymentMethod: "Phương thức thanh toán",
    cashOnDelivery: "Thanh toán khi nhận hàng",
    bankTransfer: "Chuyển khoản ngân hàng",
    selectBank: "Chọn ngân hàng",
    uploadPaymentProof: "Tải lên ảnh xác nhận chuyển khoản",
    chooseImage: "Chọn ảnh",
    placeOrder: "Đặt hàng",
    placingOrder: "Đang đặt hàng...",
    orderSuccess: "Đặt hàng thành công!",
    orderError: "Đặt hàng thất bại",
    fillAllFields: "Vui lòng điền đầy đủ thông tin",
    selectPaymentMethod: "Vui lòng chọn phương thức thanh toán",
    uploadProofRequired: "Vui lòng tải lên ảnh xác nhận chuyển khoản",
    // Address
    addressManagement: "Quản lý địa chỉ",
    saveAddress: "Lưu địa chỉ",
    editAddress: "Sửa địa chỉ",
    addressSaved: "Địa chỉ đã được lưu!",
    addressError: "Không thể lưu địa chỉ",
    nameRequired: "Vui lòng nhập tên người nhận",
    addressRequired: "Vui lòng nhập địa chỉ",
    // Search & Filter
    searchResults: "Kết quả tìm kiếm",
    filterBy: "Lọc theo",
    sortBy: "Sắp xếp theo",
    allCategories: "Tất cả danh mục",
    priceAsc: "Giá thấp đến cao",
    priceDesc: "Giá cao đến thấp",
    nameAsc: "Tên A-Z",
    nameDesc: "Tên Z-A",
    applyFilter: "Áp dụng",
    clearFilter: "Xóa lọc",
    noResults: "Không tìm thấy kết quả",
    // Order Detail
    orderInformation: "Thông tin đơn hàng",
    orderDate: "Ngày đặt",
    orderTime: "Thời gian",
    paymentInfo: "Thông tin thanh toán",
    productList: "Danh sách sản phẩm",
    subtotal: "Tạm tính",
    shippingFee: "Phí giao hàng",
    viewDetails: "Xem chi tiết",
  },
  en: {
    // Common
    home: "Home",
    orders: "Orders",
    products: "Products",
    account: "Account",
    cart: "Cart",
    settings: "Settings",
    logout: "Logout",
    search: "Search",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    confirm: "Confirm",
    back: "Back",
    all: "All",
    detail: "Detail",
    statistics: "Statistics",
    total: "Total",

    // Admin
    dashboard: "Admin Dashboard",
    orderManagement: "Order Management",
    productManagement: "Product Management",
    systemSettings: "System Settings",
    overview: "Overview",
    detailedStatistics: "Detailed Statistics",
    personalInfo: "Personal Info",
    management: "Management",
    revenue: "Revenue",
    customers: "Customers",
    totalOrders: "Total Orders",
    totalRevenue: "Total Revenue",
    totalProducts: "Total Products",

    // Order status
    pending: "Pending",
    processing: "Processing",
    completed: "Completed",
    cancelled: "Cancelled",

    // Actions
    confirmOrder: "Confirm",
    completeOrder: "Complete",
    cancelOrder: "Cancel",
    viewDetail: "Detail",

    // Settings
    theme: "Theme",
    language: "Language",
    notifications: "Notifications",
    orderNotifications: "Order Notifications",
    dataManagement: "Data",
    appearance: "Appearance",
    information: "Information",
    version: "Version",
    backupData: "Backup Data",
    clearCache: "Clear Cache",
    chooseTheme: "Choose Theme",
    chooseLanguage: "Choose Language",

    // Messages
    success: "Success",
    error: "Error",
    loading: "Loading...",
    loadingOrders: "Loading orders...",
    loadingProducts: "Loading products...",
    noData: "No data available",
    noOrders: "No orders yet",
    confirmOrderMessage: "Are you sure you want to confirm this order?",
    completeOrderMessage:
      "Confirm that the order has been successfully delivered?",
    cancelOrderMessage: "Are you sure you want to cancel this order?",
    confirmDeleteProduct: "Are you sure you want to delete product",
    paymentProof: "Payment Proof",
    no: "No",
    productAdded: "Product added successfully",
    productDeleted: "Product deleted successfully",
    cannotDeleteProduct: "Cannot delete product",
    addProduct: "Add Product",
    editProduct: "Edit Product",
    deleteProduct: "Delete product",
    confirmLogout: "Are you sure you want to logout from admin account?",
    cannotLogout: "Cannot logout. Please try again.",
    admin: "Admin",
    email: "Email",
    role: "Role",
    administrator: "Administrator",
    viewPendingOrders: "View pending orders",
    configureApp: "Configure application",
    support: "Support",
    help: "Help",
    userGuide: "User Guide",
    aboutApp: "About app",
    aboutBakeryApp: "About BakeryApp Admin",
    bakeryManagementApp: "Bakery management application",
    searchProducts: "Search products...",
    stock: "Stock",
    noProductsFound: "No products found",
    noProducts: "No products yet",
    productName: "Product Name",
    enterProductName: "Enter product name",
    price: "Price",
    enterPrice: "Enter product price",
    description: "Description",
    enterDescription: "Enter product description",
    category: "Category",
    imageURL: "Product Image URL",
    preview: "Preview",
    cannotLoadProducts: "Cannot load products list",
    fillRequiredFields: "Please fill in all required fields",
    productUpdated: "Product updated successfully",
    cannotSaveProduct: "Cannot save product",
    cannotLoadOrders: "Cannot load orders list",
    orderStatusUpdated: "Order status updated to",
    cannotUpdateOrderStatus: "Cannot update order status",
    themeChanged: "Theme changed successfully!",
    cannotChangeTheme: "Cannot change theme",
    languageChanged: "Language changed successfully!",
    cannotChangeLanguage: "Cannot change language",
    clearCacheTitle: "Clear Cache",
    clearCacheMessage:
      "Are you sure you want to clear cache? This will log you out.",
    cacheCleared: "Cache cleared",
    cannotClearCache: "Cannot clear cache",
    viewAllPendingOrders: "View all pending orders",
    freeStorage: "Free up storage space",
    noNotifications: "No new notifications",
    pendingOrdersHere: "Pending orders will be displayed here",
    cannotLoadCategories: "Cannot load categories list",
    enterCategoryName: "Please enter category name",
    categoryUpdated: "Category updated",
    categoryAdded: "Category added successfully",
    cannotSaveCategory: "Cannot save category",
    deleteCategory: "Delete category",
    confirmDeleteCategory: "Are you sure you want to delete category",
    categoryDeleteNote: "Note: Products in this category will not be deleted.",
    categoryDeleted: "Category deleted",
    cannotDeleteCategory: "Cannot delete category",
    addCategory: "Add category",
    editCategory: "Edit category",
    categoryName: "Category name",
    enterCategory: "Enter category name",
    categoryDescription: "Category description",
    enterCategoryDescription: "Enter description (optional)",
    categoryIcon: "Category icon",
    iconName: "Icon name",
    enterIconName: "E.g: pizza, fast-food, cafe",
    noCategories: "No categories yet",
    downloadYourData: "Download your data",
    notification: "Notification",
    featureInDevelopment: "Feature in development",
    searchByPhone: "Search by phone number...",

    // User screens
    myCart: "My Cart",
    emptyCart: "Cart is empty",
    emptyCartMessage: "Add products to cart",
    removeFromCart: "Remove product",
    confirmRemoveFromCart: "Remove from cart?",
    checkout: "Checkout",
    checkBeforeOrder: "Check before ordering!",
    selectAll: "Select all",
    continueShopping: "Continue shopping",
    emptyCartSubtitle: "Add some delicious cakes to your cart 🍰",
    orderNow: "Order now",
    totalAmount: "Total",
    outOfStock: "Out of stock",
    exceedsStock: "Exceeds stock",
    onlyXInStock: "Only",
    inStock: "in stock.",
    deleteProductFromCart: "Delete product",
    confirmDelete: "Delete",
    pleaseSelectProducts: "Please select at least 1 product to checkout",
    myOrders: "My Orders",
    orderHistory: "Order History",
    orderDetail: "Order Detail",
    orderCode: "Order Code",
    noOrdersYet: "No orders yet",
    ordersWillShowHere: "Your orders will be displayed here",
    completedOrdersHere: "Completed order history will be displayed here",
    orderNotFound: "Order not found",
    cancelOrderTitle: "Cancel Order",
    confirmCancelOrder: "Are you sure you want to cancel this order?",
    orderCancelled: "Order cancelled",
    cannotCancelOrder: "Cannot cancel order. Please try again.",
    confirmReceived: "Confirm received",
    confirmReceivedMessage:
      "Have you received and are satisfied with this order?",
    thankYou: "Thank you!",
    orderCompleted: "Order completed",
    reorder: "Reorder",
    cannotReorder: "Cannot reorder",
    noProductsInOrder: "No products",
    accountNumber: "Account number",
    accountHolder: "Account holder",
    pleaseCheckBank: "Please check bank account and confirm when",
    addToCart: "Add to cart",
    pleaseLogin: "Please login to add products to cart!",
    addedToCart: "Added to cart!",
    noDescription: "No description.",
    profile: "Profile",
    myAccount: "My Account",
    login: "Login",
    register: "Register",
    createAccount: "Create new account",
    alreadyHaveAccount: "Already have an account?",
    noAccountYet: "Don't have an account?",
    creating: "Creating account...",
    personalInformation: "Personal Information",
    phoneNumber: "Phone Number",
    notAvailable: "Not available",
    deliveryAddress: "Delivery Address",
    addDeliveryAddress: "Add delivery address",
    manageOrders: "Order Management",
    orderProcessing: "Processing",
    orderHistoryTab: "History",
    purchased: "Purchased",
    notLoggedIn: "You are not logged in",
    loginToExperience: "Login to experience full features",
    signUpAccount: "Sign up account",
    confirmLogoutTitle: "Confirm Logout",
    confirmLogoutMessage: "Are you sure you want to logout from your account?",
    user: "User",
    hello: "Hello",
    bakeryAppName: "Bakery App",
    deliverySlogan: "Order delicious cakes, delivered to you 🍰",
    searchPlaceholder: "Find your favorite cakes...",
    searchHistory: "🕓 Search History",
    clear: "Clear",
    noSearchHistory: "No search history yet.",
    suggestionsForYou: "🔥 Suggestions For You",
    featuredCategories: "🎂 Featured Categories",
    hotThisWeek: "🔥 Hot This Week",
    loadingData: "Loading...",
    // Login & SignUp
    emailLabel: "Email",
    enterEmail: "Enter email",
    passwordLabel: "Password",
    enterPassword: "Enter password",
    fullName: "Full Name",
    enterFullName: "Enter full name",
    phone: "Phone Number",
    enterPhone: "Enter phone number",
    confirmPassword: "Confirm Password",
    enterConfirmPassword: "Re-enter password",
    forgotPassword: "Forgot Password?",
    loginButton: "Login",
    signUpButton: "Sign Up",
    loggingIn: "Logging in...",
    signingUp: "Signing up...",
    resetPassword: "Reset Password",
    sendResetEmail: "Send Reset Email",
    emailRequired: "Please enter email",
    emailInvalid: "Invalid email address",
    passwordRequired: "Please enter password",
    passwordTooShort: "Password must be at least 6 characters",
    fullNameRequired: "Please enter full name",
    phoneRequired: "Please enter phone number",
    phoneInvalid: "Invalid phone number",
    passwordsNotMatch: "Passwords do not match",
    loginSuccess: "Login successful!",
    signUpSuccess: "Sign up successful!",
    resetEmailSent: "Password reset email sent!",
    loginError: "Login failed",
    signUpError: "Sign up failed",
    resetError: "Cannot send reset email",
    // Product Detail
    backButton: "Back",
    addToCartButton: "Add to Cart",
    buyNow: "Buy Now",
    quantity: "Quantity",
    increase: "Increase",
    decrease: "Decrease",
    productOutOfStock: "Out of Stock",
    productDescription: "Product Description",
    // Checkout
    checkoutPage: "Checkout",
    orderSummary: "Order Summary",
    recipientInfo: "Recipient Information",
    recipientName: "Recipient Name",
    recipientPhone: "Recipient Phone",
    shippingAddress: "Shipping Address",
    enterAddress: "Enter shipping address",
    paymentMethod: "Payment Method",
    cashOnDelivery: "Cash on Delivery",
    bankTransfer: "Bank Transfer",
    selectBank: "Select Bank",
    uploadPaymentProof: "Upload Payment Proof",
    chooseImage: "Choose Image",
    placeOrder: "Place Order",
    placingOrder: "Placing order...",
    orderSuccess: "Order placed successfully!",
    orderError: "Failed to place order",
    fillAllFields: "Please fill all fields",
    selectPaymentMethod: "Please select payment method",
    uploadProofRequired: "Please upload payment proof",
    // Address
    addressManagement: "Address Management",
    saveAddress: "Save Address",
    editAddress: "Edit Address",
    addressSaved: "Address saved!",
    addressError: "Cannot save address",
    nameRequired: "Please enter recipient name",
    addressRequired: "Please enter address",
    // Search & Filter
    searchResults: "Search Results",
    filterBy: "Filter By",
    sortBy: "Sort By",
    allCategories: "All Categories",
    priceAsc: "Price: Low to High",
    priceDesc: "Price: High to Low",
    nameAsc: "Name A-Z",
    nameDesc: "Name Z-A",
    applyFilter: "Apply",
    clearFilter: "Clear Filter",
    noResults: "No results found",
    // Order Detail
    orderInformation: "Order Information",
    orderDate: "Order Date",
    orderTime: "Time",
    paymentInfo: "Payment Information",
    productList: "Product List",
    subtotal: "Subtotal",
    shippingFee: "Shipping Fee",
    viewDetails: "View Details",
  },
};

interface AppContextType {
  theme: typeof themes.orange;
  themeName: keyof typeof themes;
  setTheme: (themeName: keyof typeof themes) => void;
  language: "vi" | "en";
  setLanguage: (lang: "vi" | "en") => void;
  t: (key: string) => string;
}

const AppContext = createContext<AppContextType | undefined>(undefined);

export const AppProvider = ({ children }: { children: React.ReactNode }) => {
  const [themeName, setThemeName] = useState<keyof typeof themes>("orange");
  const [language, setLanguage] = useState<"vi" | "en">("vi");

  useEffect(() => {
    loadSettings();
  }, []);

  const loadSettings = async () => {
    try {
      const savedTheme = await AsyncStorage.getItem("appTheme");
      const savedLanguage = await AsyncStorage.getItem("appLanguage");
      if (savedTheme && themes[savedTheme as keyof typeof themes]) {
        setThemeName(savedTheme as keyof typeof themes);
      }
      if (savedLanguage && (savedLanguage === "vi" || savedLanguage === "en")) {
        setLanguage(savedLanguage);
      }
    } catch (error) {
      console.error("Error loading settings:", error);
    }
  };

  const changeTheme = async (newTheme: keyof typeof themes) => {
    try {
      await AsyncStorage.setItem("appTheme", newTheme);
      setThemeName(newTheme);
    } catch (error) {
      console.error("Error saving theme:", error);
    }
  };

  const changeLanguage = async (lang: "vi" | "en") => {
    try {
      await AsyncStorage.setItem("appLanguage", lang);
      setLanguage(lang);
    } catch (error) {
      console.error("Error saving language:", error);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <AppContext.Provider
      value={{
        theme: themes[themeName],
        themeName,
        setTheme: changeTheme,
        language,
        setLanguage: changeLanguage,
        t,
      }}
    >
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error("useApp must be used within AppProvider");
  }
  return context;
};
